### ISSUE TITLE
hello world error

### ISSUE THREAD

**Issue by dpp** [dcoles/nginx-rs#1]
Howdy, I've been playing around with your code... it's pretty nifty.

However, I'm unable to get a `.so` that can be loaded into Nginx.

I updated `Cargo.toml` to change the `crate-type` to `"cdylib"` and I get a nice `libhello.so`

However, when I try to load it into Nginx, I get the following error: `2021/04/30 17:46:28 [emerg] 21462#21462: dlsym() "modules/lib_hello.so", "ngx_modules" failed (/usr/share/nginx/modules/lib_hello.so: undefined symbol: ngx_modules) in /etc/nginx/modules-enabled/50-mod-hello.conf:1`

If you could point me to instructions about how to build and load the module into Nginx, I'd appreciate it.

Thanks!

**Comment by dcoles** [comment]
Hi! Thanks for your interest!

The way I currently have this setup is for modules to be [built within the Nginx build-system](https://www.nginx.com/blog/compiling-dynamic-modules-nginx-plus/). For example:

```bash
cd nginx
./auto/configure --prefix=r --add-module=../nginx-rs/examples/hello_world
make
make install
```

(You can use `--add-dynamic-module` to generate a `.so` instead of statically linking it to the Nginx binary)

However the issue with this approach is that it [compiles the Rust module at configure time, instead of build time](https://github.com/dcoles/nginx-rs/blob/8ac995f96c7321a7efd6965b34e2e045f263f01e/examples/hello_world/config#L7), so some definitions are not set correctly. The correct approach is to probably have `config` generate a Makefile target on the fly and do the Rust build there.

However I wonder if it would be possible to generate an `.so` isolated from the Nginx build system (like you were attempting). I'll poke around and see if that's possible.

**Comment by dcoles** [comment]
Taking a deeper look, the Nginx module system normally generates the following for dynamic modules:

**`objs/ngx_http_hello_world_module_modules.c`**:
```c
#include <ngx_config.h>
#include <ngx_core.h>

extern ngx_module_t  ngx_http_hello_world_module;

ngx_module_t *ngx_modules[] = {
    &ngx_http_hello_world_module,
    NULL
};

char *ngx_module_names[] = {
    "ngx_http_hello_world_module",
    NULL
};

char *ngx_module_order[] = {
    NULL
};
```

So in theory, if we generate a `cdylib` with those additional symbols it should "just work".

**Comment by dcoles** [comment]
Switched the example over to [building a stand-alone `cdylib`](https://github.com/dcoles/nginx-rs/commit/7de0ab9cfc237bd6f51be772d4fed70a1350b6d2) and [added some documentation](https://github.com/dcoles/nginx-rs#building-modules). Let me know if that now works for you.

As you can see, there's a lot of boiler-plate required to define a module. Ideally this should be place behind a macro, rather than having every module do this work.

**Comment by dpp** [comment]
Stellar stuff!

Thank you for being so responsive... and I've got stuff building.
